/*
 * This file is part of Applied Energistics 2.
 * Copyright (c) 2013 - 2014, AlgorithmX2, All rights reserved.
 *
 * Applied Energistics 2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Applied Energistics 2 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Applied Energistics 2.  If not, see <http://www.gnu.org/licenses/lgpl>.
 */

package ae2.core.localization;

public enum ButtonToolTips implements LocalizationEnum {
    Amount,
    Toggle,
    Configure,
    Search,
    ActiveOnPulse,
    ActiveWithSignal,
    ActiveWithoutSignal,
    AlwaysActive,
    AutoExport,
    AutoExportOff,
    AutoExportOn,
    Ascending,
    BlockPlacement,
    BlockPlacementNo,
    BlockPlacementYes,
    Blocking,
    Clear,
    ClearSettings,
    CondenserOutput,
    MatterBalls,
    Craft,
    CraftEither,
    CraftOnly,
    CraftViaRedstone,
    CpuSelectionMode,
    CpuSelectionModeAny,
    CpuSelectionModePlayersOnly,
    CpuSelectionModeAutomationOnly,
    CpuStatusCoProcessor,
    CpuStatusCoProcessors,
    CpuStatusStorage,
    CpuStatusCrafting,
    CpuStatusElapsedTime,
    CpuStatusCraftedIn,
    CycleModeAction,
    Craftable,
    CraftingPlanSortMode,
    ClearProcessingSecondaryOutputs,
    ClearProcessingSecondaryOutputsTooltip,
    CycleProcessingOutput,
    CycleProcessingOutputTooltip,
    Descending,
    EmitLevelAbove,
    EmitLevelsBelow,
    EmitWhenCrafting,
    Encode,
    EncodeDescription,
    EmitterMode,
    FilterOnExtract,
    FilterOnExtractDisabled,
    FilterOnExtractEnabled,
    FillAction,
    FormationPlaneActive,
    FormationPlaneMode,
    FormationPlanePassive,
    FuzzyMode,
    FZIgnoreAll,
    FZPercent_25,
    FZPercent_50,
    FZPercent_75,
    FZPercent_99,
    InterfaceBlockingMode,
    IOMode,
    InscriberBufferHigh,
    InscriberBufferLow,
    InscriberBufferSize,
    InscriberBufferVeryLow,
    InscriberSideness,
    InscriberSidenessCombined,
    InscriberSidenessSeparate,
    InterfaceSetStockAmount,
    InterfaceTerminalDisplayMode,
    HighlightSupplier,
    HEI,
    HeiAutoPin,
    LeftClick,
    LockCraftingMode,
    LockCraftingModeNone,
    LockCraftingUntilRedstonePulse,
    LockCraftingUntilResultReturned,
    LockCraftingWhileRedstoneHigh,
    LockCraftingWhileRedstoneLow,
    MiddleClick,
    RightClick,
    MouseButton,
    ItemName,
    InventoryTweaks,
    Mod,
    NoSuchMessage,
    NonBlocking,
    NumberOfItems,
    OutputSideConfig,
    OutputSideConfigHint,
    OutputSideClear,
    OutputSideClearHint,
    OperationMode,
    OverlayMode,
    OverlayModeNo,
    OverlayModeYes,
    PartitionStorage,
    PartitionStorageHint,
    PatternUpload,
    PatternUploadHint,
    PatternUploadShiftHint,
    PatternProviderBlockingType,
    PatternProviderInsertionModeDefault,
    PatternProviderInsertionModeDefaultDescription,
    PatternProviderInsertionModePreferEmpty,
    PatternProviderInsertionModePreferEmptyDescription,
    PatternProviderInsertionModeEmptyOnly,
    PatternProviderInsertionModeEmptyOnlyDescription,
    PatternProviderOutputSideModeSingleSide,
    PatternProviderOutputSideModeSingleSideDescription,
    PatternProviderOutputSideModeSplitByIngredientsType,
    PatternProviderOutputSideModeSplitByIngredientsTypeDescription,
    PlayerPin,
    PlayerPinAddRow,
    PlayerPinRemoveRow,
    PlayerPinEmptySlot,
    PlayerPinUnpinShortcut,
    PlayerPinPinShortcut,
    PlayerPinInsertAndPinShortcut,
    PowerUnits,
    Read,
    ReadWrite,
    RedstoneMode,
    RegulateStock,
    RegulateStockOff,
    RegulateStockOn,
    ReportInaccessibleItems,
    ReportInaccessibleItemsNo,
    ReportInaccessibleItemsYes,
    RequestableAmount,
    ModifyAmountAction,
    RenameAction,
    SchedulingMode,
    SchedulingModeDefault,
    SchedulingModeRandom,
    SchedulingModeRoundRobin,
    Serial,
    SetAction,
    SelectModeAction,
    Singularity,
    ShowAllProviders,
    ShowHiddenProviders,
    ShowNonFullProviders,
    ShowVisibleProviders,
    SortBy,
    SortByCapacity,
    SortByCoProcessors,
    SortOrder,
    SortOrderAscendingDescription,
    SortOrderDescendingDescription,
    Stash,
    StashDesc,
    StashToPlayer,
    StashToPlayerDesc,
    StrongBlocking,
    NormalBlockingDescription,
    SmartBlockingDescription,
    StoreAction,
    StoredAmount,
    StoredCraftable,
    StoredItems,
    UsedResourceCountDescription,
    UsedResourcePercentDescription,
    AvailabilityDescription,
    TerminalSettings,
    TerminalStyle,
    TerminalStyle_Small,
    TerminalStyle_Medium,
    TerminalStyle_Tall,
    TerminalStyle_Full,
    TransferDirection,
    TransferToNetwork,
    TransferToStorageCell,
    Trash,
    MoveWhenEmpty,
    MoveWhenWorkIsDone,
    MoveWhenFull,
    LinkWirelessTerminal,
    PlaceWirelessBooster,
    View,
    SelectCraftingCPUFromList,
    Write;

    private final String translationKey;

    ButtonToolTips() {
        this.translationKey = "gui.tooltips.ae2." + name();
    }

    @Override
    public String getTranslationKey() {
        return this.translationKey;
    }
}
