package ae2.core.localization;

import ae2.api.config.CondenserOutput;
import ae2.api.networking.pathing.ChannelMode;
import ae2.me.AnalyserMode;
import ae2.me.netdata.LinkFlag;
import ae2.me.netdata.NodeFlag;
import ae2.parts.automation.special.ThresholdMode;
import ae2.tile.crafting.requester.RequestStatus;
import ae2.tile.misc.CanerMode;

public enum GuiText implements LocalizationEnum {
    Items,
    Amount,
    Fluids,
    Inventory,
    Config,
    CopyMode,
    CopyModeDesc,
    ExternalStorage,
    MENetworkStorage,
    AdjacentToDifferentMachines,
    And,
    AutoCrafting,
    Automatic,
    BookmarkMissing,
    BytesUsed,
    CanBeEnchanted,
    CertusQuartzObtain,
    CPUs,
    CalculatingWait,
    Cancel,
    Close,
    CantStoreItems,
    ConfirmCraftMergeAvailable,
    ConfirmCraftCpuStatus,
    ConfirmCraftNoCpu,
    CompatibleUpgrade,
    CompatibleUpgrades,
    ConfigureImportedTypes,
    ConfigureVisibleTypes,
    Condenser,
    ConfigModifier,
    CpuFallbackName,
    ConfigModifierChangeMode,
    ConfigModifierModeAdd,
    ConfigModifierModeSub,
    ConfigModifierModeMul,
    ConfigModifierModeDiv,
    ConfigModifierModeMax,
    ConfigModifierModeMin,
    ConfigModifierModeSet,
    ConfigModifierModeRmv,
    PriorityTuner,
    PriorityTunerChangeMode,
    PriorityTunerModeInput,
    PriorityTunerModeOutput,
    PriorityTunerModeIncrement,
    PriorityTunerModeDecrement,
    PriorityTunerModeInputDesc,
    PriorityTunerModeOutputDesc,
    PriorityTunerModeIncrementDesc,
    PriorityTunerModeDecrementDesc,
    PriorityTunerPriority,
    PatternModifier,
    PatternModifierMultiply,
    PatternModifierPatternMode,
    PatternModifierSubstitute,
    PatternModifierFluidSubstitute,
    PatternModifierEnable,
    PatternModifierDisable,
    PatternModifierClone,
    PatternModifierTarget,
    PatternModifierBlank,
    PatternModifierChangeMode,
    PatternModifierClear,
    PatternModifierReplace,
    PatternModifierReplaceButton,
    PatternModifierToolInventory,
    PatternModifierProviderInventory,
    PatternModifierInventorySwitch,
    PatternModifierShowPanel,
    PatternModifierHidePanel,
    PatternModifierCloneDescription,
    PatternModifierMultiplyDescription,
    PatternModifierDivideDescription,
    PatternModifierClearDescription,
    ProcessingPatternMultiplyDescription,
    ProcessingPatternDivideDescription,
    Crafting,
    CraftingCPUs,
    CraftingCpuList,
    CraftingCpuListEmpty,
    CraftingCpuListSearchTooltip,
    CraftingCpuActivityActive,
    CraftingCpuActivityFilter,
    CraftingCpuActivityInactive,
    CraftingCpuFilterAll,
    CraftingCpuHighlight,
    CraftingCpuCoreLocation,
    CraftingCpuCoreLocationInDimension,
    CraftingCpuModeFilter,
    CraftingCpuRename,
    CraftingCpuRenameAction,
    CraftingCpuSort,
    CraftingCpuSortName,
    CraftingPattern,
    ProcessingPattern,
    CraftingPlanRequests,
    CraftErrorIncompletePlan,
    CraftErrorNoCpuFound,
    CraftErrorNoSuitableCpu,
    CraftErrorNoSuitableCpuOffline,
    CraftErrorNoSuitableCpuBusy,
    CraftErrorNoSuitableCpuTooSmall,
    CraftErrorNoSuitableCpuExcluded,
    CraftErrorCpuBusy,
    CraftErrorCpuOffline,
    CraftErrorCpuTooSmall,
    CraftErrorMissingIngredient,
    CraftErrorNoCraftingPattern,
    CraftErrorReplan,
    CraftErrorRetry,
    CraftingPlan,
    CraftingStatus,
    CraftingInterface,
    CraftingCardForceCrafting,
    CraftingCardForceCraftingHint,
    CraftingCardForceCraftingDesc,
    CraftMonitorCraft,
    PseudoCraftingCardLine1,
    PseudoCraftingCardLine2,
    CraftingLockIsLocked,
    CraftingLockIsUnlocked,
    CraftingTreeTitle,
    CraftingTreeSubNodeMissing,
    CraftingTreeMissing,
    CraftingTreeScreenshot,
    CraftingTreeMissingOnly,
    CraftingTreeDefault,
    CraftingTreeBack,
    CraftingTreeLocation,
    CraftingTreeLocationInDimension,
    CraftingTreeHighlightProvider,
    CraftingTreeRenderedNodes,
    CraftingStatusHighlightSupplier,
    CraftingTreeTip0,
    CraftingTreeTip1,
    CraftingTreeTip2,
    ChannelEnergyDrain,
    ChannelModeDefault,
    ChannelModeInfinite,
    ChannelModeX2,
    ChannelModeX3,
    ChannelModeX4,
    Crafts,
    EnergyDrain,
    EnergyGenerationCapacity,
    Efficiency,
    Error,
    ExportGrid,
    Interface,
    InterfaceConfigPage,
    InterfacePagePrevious,
    InterfacePageNext,
    IOBuses,
    StorageBus,
    StorageCells,
    StorageCellTooltipUpgrades,
    PortableCells,
    PortableVoidCell,
    PortableItemCellAutoPickupTooltip,
    PortableItemCellAutoPickupHotkeyUnbound,
    WirelessTerminals,
    Excluded,
    FromStorage,
    InventoryUsage,
    ForceMerge,
    ForceStart,
    ForceStartHoldShift,
    Fuzzy,
    Included,
    IntermediateCraft,
    HeiCraftIngredientTooltip,
    HeiRetrieveIngredientTooltip,
    InvalidNumber,
    InvalidPattern,
    InvalidSingularity,
    Linked,
    Missing,
    MeteoriteCompassBeacon,
    MeteoriteCompassBeaconHint,
    MeteoriteCompassBeaconUpgradeHint,
    MeteoriteCraterNone,
    MeteoriteCraterNormal,
    MeteoriteCraterLava,
    MeteoriteCraterObsidian,
    MeteoriteCraterWater,
    MeteoriteCraterSnow,
    MeteoriteCraterIce,
    MeteoriteFalloutNone,
    MeteoriteFalloutDefault,
    MeteoriteFalloutSand,
    MeteoriteFalloutTerracotta,
    MeteoriteFalloutIceSnow,
    Merge,
    Next,
    NetworkDetails,
    NetworkTool,
    NoCraftingCPUs,
    NoChannel,
    NumberGreaterThanMaxValue,
    NumberLessThanMinValue,
    NumberNonInteger,
    NumberEntryButtonSettings,
    NumberEntryButtonSettingsDefault,
    NumberEntryButtonSettingsShift,
    NumberEntryButtonSettingsCtrl,
    NumberEntryButtonSettingsAlt,
    NumberEntryButtonSettingsReset,
    NumberEntryCeil,
    NumberEntryFloor,
    Of,
    Or,
    OutOfPower,
    OutputSides,
    OutputSideToggleHint,
    OutputSideUnavailable,
    OutputSideEnabled,
    OutputSideDisabled,
    PartialPlan,
    Partitioned,
    PatternAccessTerminal,
    PatternAccessTerminalHint,
    PatternAccessTerminalShort,
    PatternAccessTerminalHighlightProvider,
    PatternAccessTerminalOpenProvider,
    PatternAccessTerminalSearchTooltipInput,
    PatternAccessTerminalSearchTooltipOutput,
    PatternAccessTerminalProviderSearchTooltip,
    PatternAccessTerminalToggleVisibility,
    PatternAccessTerminalRenameProvider,
    PatternProviderPagePrevious,
    PatternProviderPageNext,
    PatternAmountTimesName,
    RequesterTerminal,
    RequesterTerminalShort,
    RequesterFallbackName,
    RequesterNoRequesters("requester.no_requesters"),
    RequesterAmount("requester.amount"),
    RequesterBatch("requester.batch"),
    RequesterSubmit("requester.submit"),
    RequesterToggleDisabled("requester.toggle.disabled"),
    RequesterToggleEnabled("requester.toggle.enabled"),
    RequesterForceStartDetailOn("requester.ForceStartDetailOn"),
    RequesterForceStartDetailOff("requester.ForceStartDetailOff"),
    RequesterStatus("requester.status"),
    RequesterStatusShift("requester.status.shift"),
    RequesterStatusIdle("requester.status.idle"),
    RequesterStatusIdleDesc("requester.status.idle.desc"),
    RequesterStatusMissing("requester.status.missing"),
    RequesterStatusMissingDesc("requester.status.missing.desc"),
    RequesterStatusNoPattern("requester.status.no_pattern"),
    RequesterStatusNoPatternDesc("requester.status.no_pattern.desc"),
    RequesterStatusCpu("requester.status.cpu"),
    RequesterStatusCpuDesc("requester.status.cpu.desc"),
    RequesterStatusCrafting("requester.status.crafting"),
    RequesterStatusCraftingDesc("requester.status.crafting.desc"),
    RequesterStatusExporting("requester.status.exporting"),
    RequesterStatusExportingDesc("requester.status.exporting.desc"),
    PatternImportPrioritiesTitle,
    PatternImportPriorityHeiBookmarks("PatternImportPriorityHeiBookmarks"),
    PatternImportPriorityHeiBookmarksDesc("PatternImportPriorityHeiBookmarks.desc"),
    PatternImportPriorityCraftables("PatternImportPriorityCraftables"),
    PatternImportPriorityCraftablesDesc("PatternImportPriorityCraftables.desc"),
    PatternImportPriorityStored("PatternImportPriorityStored"),
    PatternImportPriorityStoredDesc("PatternImportPriorityStored.desc"),
    PatternTooltipFluidSubstitutions,
    PatternTooltipSubstitutions,
    Patterns,
    Precise,
    PressShiftForFullList,
    Priority,
    PriorityExtractionHint,
    PriorityInsertionHint,
    WorkInterval,
    WorkIntervalHint,
    Resume,
    ReturnToPreviousGui,
    ReturnInventory,
    Scheduled,
    SearchSettingsAutoFocus,
    SearchSettingsClearExternal,
    SearchSettingsRememberSearch,
    SearchSettingsReplaceWithExternal,
    SearchSettingsSyncWithExternal,
    SearchSettingsTitle,
    SearchSettingsUseExternalSearch,
    SearchSettingsUseInternalSearch,
    SearchPlaceholder,
    SearchTooltip,
    SearchTooltipItemId,
    SearchTooltipModId,
    SearchTooltipTag,
    SearchTooltipToolTips,
    SetAmountButtonHint,
    SelectAmount,
    SelectFromList,
    Set,
    CellRestriction,
    CellRestrictionResourceTotal,
    CellRestrictionMaxAmount,
    CellRestrictionMaxType,
    CellRestrictionAmountPerByte,
    CellRestrictionTypePerByte,
    CellRestrictionAllocatedByte,
    CellRestrictionMaxByte,
    CellRestrictionFreeByte,
    CellRestrictionAmount,
    CellRestrictionTypes,
    ResetRestriction,
    ResetRestrictionHint,
    RestrictedSuffix,
    SpatialAnchor,
    SpatialAnchorAll,
    SpatialAnchorAllLoaded,
    SpatialAnchorLoadedChunks,
    SpatialAnchorStatistics,
    SpatialAnchorUsedPower,
    SpatialCapacity,
    SpatialCellEmpty,
    SpatialIOPort,
    SpatialSerialNumber,
    SpatialStoredSize,
    AnnihilationPlane,
    ThresholdLevelEmitter,
    ThresholdLevelEmitterUpper,
    ThresholdLevelEmitterLower,
    PutAQuartzTool,
    PutAFluixBlock,
    QuartzTools,
    IntrinsicEnchant,
    IncreasedEnergyUseFromEnchants,
    Installed,
    inWorldCraftingPresses,
    RequiredPower,
    Renamer,
    Recipe,
    RecipeType,
    SelectedCraftingCPU,
    SCSInvalid,
    SCSSize,
    Start,
    StartWithoutMergingHoldCtrl,
    Suspend,
    TerminalSettingsTitle,
    TerminalSettingsPinAutoCraftedItems,
    TerminalSettingsPinDisplaySortTop,
    TerminalSettingsPinDisplaySortTopTooltip,
    TerminalSettingsPinDisplayLockedGrid,
    TerminalSettingsPinDisplayLockedGridTooltip,
    TerminalSettingsNotifyForFinishedJobs,
    TerminalSettingsClearGridOnClose,
    TerminalSettingsAutoFillBlankPatterns,
    TerminalSettingsRecursiveIngredientReserve,
    TerminalSettingsRecursiveIngredientReserveTooltip,
    TerminalSettingsPlayerPinRows,
    TerminalSettingsPlayerPinRowsTooltip,
    TerminalViewCellsTooltip,
    ViewCellEnabled,
    ViewCellToggleHint,
    ToCraft,
    ToastCraftingJobFinishedTitle,
    ToastCraftingJobFinishedText,
    PowerInputRate,
    StoredEnergy,
    StoredPower,
    MaxPower,
    PowerUsageRate,
    Produces,
    Types,
    Unlinked,
    UpgradeToolbelt,
    Wireless,
    WirelessTerminalBridgeMissing,
    WirelessTerminalBridgeUnpowered,
    WirelessTerminalCurrent,
    WirelessTerminalDifferentNetwork,
    WirelessTerminalNoSingularity,
    WirelessTerminalSelector,
    WirelessTerminalSettingsTitle,
    WirelessTerminalSettingsPickBlock,
    WirelessTerminalSettingsCraftIfMissing,
    WirelessTerminalSettingsRestock,
    WirelessTerminalSettingsMagnet,
    WirelessTerminalSettingsPickupToME,
    WirelessMagnetTitle,
    WirelessMagnetPickup,
    WirelessMagnetInsert,
    WirelessMagnetConfigure,
    WirelessMagnetPickupWhitelist,
    WirelessMagnetPickupBlacklist,
    WirelessMagnetInsertWhitelist,
    WirelessMagnetInsertBlacklist,
    WirelessMagnetCopyPickup,
    WirelessMagnetCopyInsert,
    WirelessMagnetSwap,
    PortableCellPickupFilterTitle,
    PortableCellPickupFilterConfigure,
    PortableCellPickupFilterWhitelist,
    PortableCellPickupFilterBlacklist,
    PortableCellPickupFilterClear,
    WirelessRange,
    ThroughputMonitorValueTick("ValueTick"),
    ThroughputMonitorValueSecond("ValueSecond"),
    ThroughputMonitorValueMinute("ValueMinute"),
    ThroughputMonitorValueTenMinute("ValueTenMinute"),
    ThroughputMonitorRoutineTick("RoutineTick"),
    ThroughputMonitorRoutineSecond("RoutineSecond"),
    ThroughputMonitorRoutineMinute("RoutineMinute"),
    ThroughputMonitorRoutineTenMinute("RoutineTenMinute"),
    NetworkAnalyserReset("network_analyser.reset"),
    NetworkAnalyserStateNormalNodes("network_analyser.state.normal_nodes"),
    NetworkAnalyserStateDenseNodes("network_analyser.state.dense_nodes"),
    NetworkAnalyserStateMissingNodes("network_analyser.state.missing_nodes"),
    NetworkAnalyserModeFull("network_analyser.mode.FULL"),
    NetworkAnalyserModeNodes("network_analyser.mode.NODES"),
    NetworkAnalyserModeChannels("network_analyser.mode.CHANNELS"),
    NetworkAnalyserModeNoNum("network_analyser.mode.NONUM"),
    NetworkAnalyserModeP2p("network_analyser.mode.P2P"),
    NetworkAnalyserLinkNormal("network_analyser.LINK.NORMAL"),
    NetworkAnalyserLinkDense("network_analyser.LINK.DENSE"),
    NetworkAnalyserLinkCompressed("network_analyser.LINK.COMPRESSED"),
    NetworkAnalyserNodeNormal("network_analyser.NODE.NORMAL"),
    NetworkAnalyserNodeDense("network_analyser.NODE.DENSE"),
    NetworkAnalyserNodeMissing("network_analyser.NODE.MISSING"),
    NetworkAnalyserChannelInfinite("network_analyser.channel.INFINITE"),
    NetworkAnalyserChannelDefault("network_analyser.channel.DEFAULT"),
    NetworkAnalyserChannelX2("network_analyser.channel.X2"),
    NetworkAnalyserChannelX3("network_analyser.channel.X3"),
    NetworkAnalyserChannelX4("network_analyser.channel.X4"),
    TickAnalyserStart("tick_analyser.start"),
    TickAnalyserCancel("tick_analyser.cancel"),
    TickAnalyserRate("tick_analyser.rate"),
    VoidCellModeTrash("VoidCell.mode.0"),
    VoidCellModeMatterBall("VoidCell.mode.1"),
    VoidCellModeSingularity("VoidCell.mode.2"),
    VoidCellOpenGui("VoidCell.OpenGui"),
    ModFilterTooltip,
    ODFilterBlackTooltip,
    ODFilterWhiteTooltip,
    PreciseBusSetAmount,
    ThresholdGreater,
    ThresholdLower,
    CrystalAssemblerAmount,
    CanerFill("caner.fill"),
    CanerEmpty("caner.empty"),
    MysteriousQuote,
    NotSoMysteriousQuote,
    Nothing,
    AttachedTo,
    Unattached,
    AdvancedMemoryCardTitle("advanced_memory_card.title"),
    AdvancedMemoryCardEmpty("advanced_memory_card.empty"),
    AdvancedMemoryCardFilterEmpty("advanced_memory_card.filter_empty"),
    AdvancedMemoryCardBind("advanced_memory_card.bind"),
    AdvancedMemoryCardUnbind("advanced_memory_card.unbind"),
    AdvancedMemoryCardName("advanced_memory_card.name"),
    AdvancedMemoryCardType("advanced_memory_card.type"),
    AdvancedMemoryCardFrequency("advanced_memory_card.frequency"),
    AdvancedMemoryCardPos("advanced_memory_card.pos"),
    AdvancedMemoryCardSide("advanced_memory_card.side"),
    AdvancedMemoryCardDim("advanced_memory_card.dim"),
    AdvancedMemoryCardNotSet("advanced_memory_card.not_set"),
    AdvancedMemoryCardBound("advanced_memory_card.bound"),
    AdvancedMemoryCardUnbound("advanced_memory_card.unbound"),
    AdvancedMemoryCardOffline("advanced_memory_card.offline"),
    AdvancedMemoryCardUnknown("advanced_memory_card.unknown"),
    AdvancedMemoryCardModeOutput("advanced_memory_card.mode.output"),
    AdvancedMemoryCardModeInput("advanced_memory_card.mode.input"),
    AdvancedMemoryCardModeCopy("advanced_memory_card.mode.copy"),
    AdvancedMemoryCardModeDelete("advanced_memory_card.mode.delete"),
    AdvancedMemoryCardFilterAny("advanced_memory_card.filter_any"),
    AdvancedMemoryCardFilterType("advanced_memory_card.filter_type"),
    AdvancedMemoryCardFilterTypes("advanced_memory_card.filter_types"),
    AdvancedMemoryCardFilterHint("advanced_memory_card.filter_hint"),
    AdvancedMemoryCardStatus("advanced_memory_card.status"),
    AdvancedMemoryCardStatusAny("advanced_memory_card.status_any"),
    AdvancedMemoryCardStatusInput("advanced_memory_card.status_input"),
    AdvancedMemoryCardStatusOutput("advanced_memory_card.status_output"),
    AdvancedMemoryCardStatusUnbound("advanced_memory_card.status_unbound"),
    AdvancedMemoryCardTypeAny("advanced_memory_card.type_any"),
    AdvancedMemoryCardRefresh("advanced_memory_card.refresh"),
    AdvancedMemoryCardSearchTooltip("advanced_memory_card.search_tooltip"),
    AdvancedMemoryCardChangeTypeHint("advanced_memory_card.change_type_hint"),
    AdvancedMemoryCardRenameHint("advanced_memory_card.rename_hint"),
    P2PAttunementEnergy,
    P2PAttunementFluid,
    TankBucketCapacity,
    With,
    Yes,
    No,
    IncompatibleWithCell,
    CantFitInsideStorageCell,
    CraftTree;

    private final String translationKey;

    GuiText() {
        this.translationKey = "gui.ae2." + name();
    }

    GuiText(String translationKeySuffix) {
        this.translationKey = "gui.ae2." + translationKeySuffix;
    }

    public static GuiText requesterStatus(RequestStatus status) {
        return switch (status) {
            case IDLE, REQUESTING, PLANNING -> RequesterStatusIdle;
            case MISSING -> RequesterStatusMissing;
            case NO_PATTERN -> RequesterStatusNoPattern;
            case CPU -> RequesterStatusCpu;
            case CRAFTING -> RequesterStatusCrafting;
            case EXPORTING -> RequesterStatusExporting;
        };
    }

    public static GuiText requesterStatusDescription(RequestStatus status) {
        return switch (status) {
            case IDLE, REQUESTING, PLANNING -> RequesterStatusIdleDesc;
            case MISSING -> RequesterStatusMissingDesc;
            case NO_PATTERN -> RequesterStatusNoPatternDesc;
            case CPU -> RequesterStatusCpuDesc;
            case CRAFTING -> RequesterStatusCraftingDesc;
            case EXPORTING -> RequesterStatusExportingDesc;
        };
    }

    public static GuiText networkAnalyserMode(AnalyserMode mode) {
        return switch (mode) {
            case FULL -> NetworkAnalyserModeFull;
            case NODES -> NetworkAnalyserModeNodes;
            case CHANNELS -> NetworkAnalyserModeChannels;
            case NONUM -> NetworkAnalyserModeNoNum;
            case P2P -> NetworkAnalyserModeP2p;
        };
    }

    public static GuiText networkAnalyserChannel(ChannelMode mode) {
        return switch (mode) {
            case INFINITE -> NetworkAnalyserChannelInfinite;
            case DEFAULT -> NetworkAnalyserChannelDefault;
            case X2 -> NetworkAnalyserChannelX2;
            case X3 -> NetworkAnalyserChannelX3;
            case X4 -> NetworkAnalyserChannelX4;
        };
    }

    public static GuiText networkAnalyserLabel(Enum<?> type) {
        if (type instanceof LinkFlag linkFlag) {
            return switch (linkFlag) {
                case NORMAL -> NetworkAnalyserLinkNormal;
                case DENSE -> NetworkAnalyserLinkDense;
                case COMPRESSED -> NetworkAnalyserLinkCompressed;
            };
        }

        return switch ((NodeFlag) type) {
            case NORMAL -> NetworkAnalyserNodeNormal;
            case DENSE -> NetworkAnalyserNodeDense;
            case MISSING -> NetworkAnalyserNodeMissing;
        };
    }

    public static GuiText voidCellMode(CondenserOutput output) {
        return switch (output) {
            case TRASH -> VoidCellModeTrash;
            case MATTER_BALLS -> VoidCellModeMatterBall;
            case SINGULARITY -> VoidCellModeSingularity;
        };
    }

    public static GuiText thresholdMode(ThresholdMode mode) {
        return switch (mode) {
            case GREATER -> ThresholdGreater;
            case LOWER -> ThresholdLower;
        };
    }

    public static GuiText canerMode(CanerMode mode) {
        return switch (mode) {
            case FILL -> CanerFill;
            case EMPTY -> CanerEmpty;
        };
    }

    @Override
    public String getTranslationKey() {
        return this.translationKey;
    }
}
